# Generated by Django 4.2.13 on 2024-06-21 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('credential_id', models.CharField(blank=True, max_length=255, null=True)),
                ('credential_public_key', models.TextField(blank=True, null=True)),
                ('sign_count', models.IntegerField(default=0)),
            ],
        ),
    ]
