# Generated by Django 4.2.13 on 2024-06-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('credential_id', models.BinaryField()),
                ('credential_public_key', models.BinaryField()),
                ('sign_count', models.IntegerField(default=0)),
            ],
        ),
    ]
